### ISSUE TITLE
`WebSocket is closed before the connection is established` on chatroom page load

### ISSUE THREAD

**Issue by andkon** [jacobian/channels-example#2]
On loading [chat](https://django-channels-example.herokuapp.com/holy-shape-0462/?), the first message attempted to send shows this error in console (Chrome):
```
WebSocket connection to 'wss://django-channels-example.herokuapp.com/chat/holy-shape-0462/' failed: WebSocket is closed before the connection is established.
```
If you show attempt to send a message, it shows this error and seems to refresh the page:
```
Uncaught INVALID_STATE_ERR : Pausing to reconnect websocket
Navigated to https://django-channels-example.herokuapp.com/holy-shape-0462/?
```
Also happens in Safari.

**Comment by jacobian** [comment]
I'm thinking this was happening because the app was sleeping, and the initial connection didn't wake the app. I've upgraded to hobby dynos and I'm no longer getting the error, so... let's call this fixed?
