### ISSUE TITLE
ConnectionError: Error 61 connecting to localhost:6379. Connection refused. on channels version upgrade

### ISSUE THREAD

**Issue by guialante** [jacobian/channels-example#7]
I just upgrade channels to current version 0.10.1 and start getting ConnectionError: Error 61 connecting to localhost:6379. Connection refused, using `python manage.py runserver ` it was working flawless with current requirements.txt configuration.

**Comment by nordbit** [comment]
You got a problem with redis connection(?)
Do You upgraded rest of requirements as well? Daphne server, asgi_redis connector  and asgiref?
From readme of channels:
```
(Note: Recent versions of Channels also need recent versions of Daphne, asgi_redis and asgiref, so make sure you update all at once)
```

**Comment by guialante** [comment]
I upgrade channels using: `pip install -U channels`, I gonna test integrating current channels version in other django project using examples of this project to see if the problem is for channels-example or channels app.

**Comment by nordbit** [comment]
Try change settings.py from redis backend to inmemory backend:
```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgiref.inmemory.ChannelLayer",
        "ROUTING": "myproject.routing.channel_routing",
    },
}
```
